In [212]:
from models.arcs import load_alt_model_a, load_alt_model_b, load_inf_model, GenPhiloText
from utilities.loaders import load_file
from utilities.preprocessors import preprocess, map_value_to_index, init_sequences_a, init_sequences_b
from utilities.visualizers import export_results

from tensorflow.keras.losses import CategoricalCrossentropy as cce_loss
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import CategoricalAccuracy, CategoricalCrossentropy as cce_metric

from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow import one_hot

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [213]:
corpus = load_file('./data/notes.txt')

In [214]:
corpus[:500]

'A simple idea “What is the meaning of life?”\nI asked as I learned through the works of Camus? \nOne step down, I felt a yearning of meaning in this world.\nIn this yearning I stumbled upon eastern philosophy;\nIkigai as the Japanese philosophers called it was a considerable way for me to find meaning at that certain point in my life. \nFollowed then another idea, a leap of faith as Kierkegaard would call it, yet I had no idea this was his idea. \nCalm followed after the storm, and then I took another'

In [215]:
len(corpus)

226750

In [216]:
chars = sorted(list(set(corpus)))
chars

['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '/',
 '0',
 '1',
 '2',
 '3',
 '4',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'Y',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '´',
 'ç',
 'é',
 'ï',
 '–',
 '—',
 '‘',
 '’',
 '“',
 '”',
 '…']

# Preprocessing corpus
* replace quotation marks like this '“'/'”' with this instead '"'
* replace single quotation marks like this '‘'/'’' with ''' instead
* replace this hyphen '–' with this hyphen '—'
* lowercase all words (for now)
* replace 3 consecutive '.' with  '…' instead

In [217]:
corpus = preprocess(corpus)
corpus[:500]

'a simple idea "what is the meaning of life?"\ni asked as i learned through the works of camus? \none step down, i felt a yearning of meaning in this world.\nin this yearning i stumbled upon eastern philosophy;\nikigai as the japanese philosophers called it was a considerable way for me to find meaning at that certain point in my life. \nfollowed then another idea, a leap of faith as kierkegaard would call it, yet i had no idea this was his idea. \ncalm followed after the storm, and then i took another'

In [218]:
len(corpus)

226961

In [219]:
chars = sorted(list(set(corpus)))
chars = ['[UNK]'] + chars
chars

['[UNK]',
 '\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '/',
 '0',
 '1',
 '2',
 '3',
 '4',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '?',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '´',
 'ç',
 'é',
 'ï',
 '—',
 '…']

In [220]:
n_unique = len(chars)

# Creating mapper from a unique character to its respective index

In [221]:
char_to_idx = map_value_to_index(chars, len(chars), 0)
idx_to_char = map_value_to_index(chars, len(chars), 0, inverted=True)

In [222]:
char_to_idx

{'[UNK]': 0,
 '\n': 1,
 ' ': 2,
 '!': 3,
 '"': 4,
 '&': 5,
 "'": 6,
 '(': 7,
 ')': 8,
 ',': 9,
 '-': 10,
 '.': 11,
 '/': 12,
 '0': 13,
 '1': 14,
 '2': 15,
 '3': 16,
 '4': 17,
 '6': 18,
 '7': 19,
 '8': 20,
 '9': 21,
 ':': 22,
 ';': 23,
 '?': 24,
 'a': 25,
 'b': 26,
 'c': 27,
 'd': 28,
 'e': 29,
 'f': 30,
 'g': 31,
 'h': 32,
 'i': 33,
 'j': 34,
 'k': 35,
 'l': 36,
 'm': 37,
 'n': 38,
 'o': 39,
 'p': 40,
 'q': 41,
 'r': 42,
 's': 43,
 't': 44,
 'u': 45,
 'v': 46,
 'w': 47,
 'x': 48,
 'y': 49,
 'z': 50,
 '´': 51,
 'ç': 52,
 'é': 53,
 'ï': 54,
 '—': 55,
 '…': 56}

In [223]:
idx_to_char

{0: '[UNK]',
 1: '\n',
 2: ' ',
 3: '!',
 4: '"',
 5: '&',
 6: "'",
 7: '(',
 8: ')',
 9: ',',
 10: '-',
 11: '.',
 12: '/',
 13: '0',
 14: '1',
 15: '2',
 16: '3',
 17: '4',
 18: '6',
 19: '7',
 20: '8',
 21: '9',
 22: ':',
 23: ';',
 24: '?',
 25: 'a',
 26: 'b',
 27: 'c',
 28: 'd',
 29: 'e',
 30: 'f',
 31: 'g',
 32: 'h',
 33: 'i',
 34: 'j',
 35: 'k',
 36: 'l',
 37: 'm',
 38: 'n',
 39: 'o',
 40: 'p',
 41: 'q',
 42: 'r',
 43: 's',
 44: 't',
 45: 'u',
 46: 'v',
 47: 'w',
 48: 'x',
 49: 'y',
 50: 'z',
 51: '´',
 52: 'ç',
 53: 'é',
 54: 'ï',
 55: '—',
 56: '…'}

In [224]:
n_time_steps = 100
X, Y = init_sequences_a(corpus, char_to_idx, T_x=n_time_steps)
X

array([[25,  2, 43, ..., 29,  2, 43],
       [ 2, 43, 33, ...,  2, 43, 44],
       [43, 33, 37, ..., 43, 44, 29],
       ...,
       [39, 42,  2, ..., 29, 36, 33],
       [42,  2, 44, ..., 36, 33, 29],
       [ 2, 44, 42, ..., 33, 29, 30]])

In [225]:
X.shape

(226861, 100)

In [226]:
Y

array([44, 29, 40, ..., 29, 30, 11])

# convert Y data's indeces to their one hot vector representation

In [227]:
Y = one_hot(Y, depth=n_unique)
Y

<tf.Tensor: shape=(226861, 57), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

In [228]:
Y[3]

<tf.Tensor: shape=(57,), dtype=float32, numpy=
array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.], dtype=float32)>

In [229]:
# number of examples
len(X)

226861

In [230]:
len(X[-1])

100

# Instantiate generative model A with set architecture

In [231]:
emb_dim = 64
n_a = 32

In [232]:
model = load_alt_model_a(n_unique=n_unique, T_x=n_time_steps, emb_dim=emb_dim, n_a=n_a, keep_prob=0.8, lambda_=0.1)
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_7 (Embedding)     (None, 100, 64)           3648      
                                                                 
 lstm_14 (LSTM)              (None, 100, 32)           12416     
                                                                 
 lstm_15 (LSTM)              (None, 32)                8320      
                                                                 
 dense_7 (Dense)             (None, 57)                1881      
                                                                 
 batch_normalization_7 (Bat  (None, 57)                228       
 chNormalization)                                                
                                                                 
 activation_7 (Activation)   (None, 57)                0         
                                                      

# Provide loss, optimizer, and metrics for both alternative models A and B

In [233]:
opt = Adam(learning_rate=0.001, beta_1=0.9, beta_2=0.999)
loss = cce_loss()
metrics = [CategoricalAccuracy(), cce_metric()]

# model.compile(loss=loss, optimizer=opt, metrics=metrics)

# Train alternative model A and checkpoint weights

In [234]:
# weights_path = "./weights/weights-improvement-{epoch:02d}-{categorical_accuracy:.4f}.hdf5"
# checkpoint = ModelCheckpoint(weights_path, monitor='categorical_accuracy', verbose=1, save_best_only=True, mode='max')
# callbacks_list = [checkpoint]

In [235]:
# history = model.fit(X, Y, epochs=20, batch_size=2048, callbacks=callbacks_list)

In [236]:
# export_results(history, ['loss'], image_only=False)
# export_results(history, ['categorical_accuracy'], image_only=False)

# Preprocessing for alternative model B

In [238]:
X, Y = init_sequences_b(corpus, char_to_idx, T_x=n_time_steps)
X

[[25,
  2,
  43,
  33,
  37,
  40,
  36,
  29,
  2,
  33,
  28,
  29,
  25,
  2,
  4,
  47,
  32,
  25,
  44,
  2,
  33,
  43,
  2,
  44,
  32,
  29,
  2,
  37,
  29,
  25,
  38,
  33,
  38,
  31,
  2,
  39,
  30,
  2,
  36,
  33,
  30,
  29,
  24,
  4,
  1,
  33,
  2,
  25,
  43,
  35,
  29,
  28,
  2,
  25,
  43,
  2,
  33,
  2,
  36,
  29,
  25,
  42,
  38,
  29,
  28,
  2,
  44,
  32,
  42,
  39,
  45,
  31,
  32,
  2,
  44,
  32,
  29,
  2,
  47,
  39,
  42,
  35,
  43,
  2,
  39,
  30,
  2,
  27,
  25,
  37,
  45,
  43,
  24,
  2,
  1,
  39,
  38,
  29,
  2,
  43],
 [29,
  40,
  2,
  28,
  39,
  47,
  38,
  9,
  2,
  33,
  2,
  30,
  29,
  36,
  44,
  2,
  25,
  2,
  49,
  29,
  25,
  42,
  38,
  33,
  38,
  31,
  2,
  39,
  30,
  2,
  37,
  29,
  25,
  38,
  33,
  38,
  31,
  2,
  33,
  38,
  2,
  44,
  32,
  33,
  43,
  2,
  47,
  39,
  42,
  36,
  28,
  11,
  1,
  33,
  38,
  2,
  44,
  32,
  33,
  43,
  2,
  49,
  29,
  25,
  42,
  38,
  33,
  38,
  31,
  2,
  33,
  2,
  43,


In [239]:
len(X)

2248

In [240]:
len(X[-2])

100

In [241]:
len(X[-1])

100

In [242]:
len(Y[-1])

100

In [244]:
X[-1]

[25,
 35,
 43,
 2,
 37,
 49,
 2,
 26,
 29,
 36,
 33,
 29,
 30,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]